export const ENDPOINTS = {
  authMobileLogin: '/api/auth?action=mobile-login',
  authSession: '/api/auth?action=session',
  authLogout: '/api/auth?action=logout',
  bootstrap: '/api/bootstrap',
  clockIn: '/api/clocking?action=clock-in',
  pendingClockIn: '/api/clocking?action=pending-clock-in',
  finalizeClockIn: '/api/clocking?action=clock-in-finalize',
  clockOut: '/api/clocking?action=clock-out',
  pendingClockOut: '/api/clocking?action=pending-clock-out',
  finalizeClockOut: '/api/clocking?action=clock-out-finalize',
  switchActivity: '/api/clocking?action=switch-activity',
  activeUnbillableCategories: '/api/clocking?action=active-unbillable-categories',
  timeCorrectionsCreate: '/api/time-corrections?action=create',
  timeCorrectionsList: '/api/time-corrections?action=list&mine=true',
  timeCorrectionsEffectiveTimeEntries: '/api/time-corrections?action=effective-time-entries',
  timeOffRequests: '/api/time-off-requests',
  employeeForms: '/api/employee?action=forms',
  employeeRequiredForms: '/api/employee?action=required',
  employeeFormSubmission: '/api/employee?action=submission',
  employeeFormSubmit: '/api/employee?action=submit',
  storage: '/api/storage',
} as const;
